# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def even_fib_sum(max_value)
	fib_nums = [0,1]
		while fib_nums.last < max_value do
		    fib_nums << fib_nums[-2] + fib_nums[-1]
		end
	fib_nums.pop 
 	fib_nums.inject do |sum, n| 
		if n%2 == 0
			sum + n
		else
			sum
		end
	end    
end

p even_fib_sum(4000000) == 4613732 #=> true